name: terraform-ci

on:
  pull_request:
    paths:
      - "envs/**"
      - "modules/**"
      - ".github/workflows/terraform-ci.yml"

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack:
          - envs/dev
          - envs/dev-addons
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: fmt
        run: terraform -chdir=${{ matrix.stack }} fmt -check -recursive

      - name: init (no backend)
        run: terraform -chdir=${{ matrix.stack }} init -backend=false

      - name: validate
        run: terraform -chdir=${{ matrix.stack }} validate
